modLoader="javafml" #mandatory
loaderVersion="[1,)" #mandatory
license = "All Rights Reserved"

[[mods]] #mandatory
modId="mute" #mandatory
version = "${version}" #mandatory
displayName="Mute" #mandatory
authors="Sunekaer" #optional
description='''
Mutes sounds in the game based on config.
'''

[[dependencies.mute]]
modId = "neoforge"
required = true
versionRange = "[20.4,)"
ordering="NONE"
side="BOTH"

[[dependencies.mute]]
modId="minecraft"
required=true
versionRange="[1.20.4,)"
ordering="NONE"
side="BOTH"