modLoader="javafml" #mandatory
loaderVersion="[4,)" #mandatory
license = "All Rights Reserved"
displayTest="IGNORE_ALL_VERSION"

[[mods]] #mandatory
modId="mute" #mandatory
version = "${version}" #mandatory
displayName="Mute" #mandatory
authors="Sunekaer" #optional
description='''
Mutes sounds in the game based on config.
'''
side="CLIENT"

[[dependencies.mute]]
modId = "neoforge"
required = true
versionRange = "[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.mute]]
modId="minecraft"
required=true
versionRange="[1.21,)"
ordering="NONE"
side="BOTH"